# ── Imports ────────────────────────────────────────────────
include themes/catppuccin-mocha.conf

# ── Font ───────────────────────────────────────────────────
font_family      Hack Nerd Font Mono Regular
bold_font        Hack Nerd Font Mono Bold
italic_font      Hack Nerd Font Mono Italic
bold_italic_font Hack Nerd Font Mono Bold Italic
font_size        12.0

adjust_line_height  1

# ── Colors ─────────────────────────────────────────────────
draw_bold_text_with_bright_colors yes

# ── Scrollback ─────────────────────────────────────────────
scrollback_lines 5000

# ── Window ─────────────────────────────────────────────────
window_padding_width 4
title Kitty

# Mac
macos_option_as_alt left 

# ── Term ───────────────────────────────────────────────────
term xterm-kitty

