# ── Imports ────────────────────────────────────────────────
include themes/catppuccin-mocha.conf

# ── Font ───────────────────────────────────────────────────
font_family      Hack Regular
bold_font        Hack Bold
italic_font      Hack Italic
bold_italic_font Hack Bold Italic
font_size        10.0

adjust_line_height  1

# ── Colors ─────────────────────────────────────────────────
draw_bold_text_with_bright_colors yes

# ── Scrollback ─────────────────────────────────────────────
scrollback_lines 5000

# ── Window ─────────────────────────────────────────────────
window_padding_width 4
title Kitty

# ── Term ───────────────────────────────────────────────────
term xterm-kitty
